version: '3'
services:
  db:
    image: mysql:8.0
    container_name: "mysql"
    # M1 Macの場合必要
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      APP_ENV: "development"
    env_file:
      - .env.development
    volumes:
      - ./log/db:/var/log/mysql
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./api:/src/api
      - ./scripts:/src/scripts
    ports:
      - 8080:8000
    depends_on:
      - db
    environment:
      APP_ENV: "development"
    env_file:
      - .env.development
    working_dir: /src/scripts
    command: bash -c "./run.sh"
volumes:
  mysql_data:
