version: '3'
services:
  db:
    image: mysql:8.0
    container_name: "mysql"
    # M1 Macの場合必要
    platform: linux/amd64
    environment:
      # MYSQL_USER: user
      # MYSQL_PASSWORD: root
      # MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'demo'
      TZ: Asia/Tokyo
    # env_file:
    #   - .env.development
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./api:/src/api
      - ./scripts:/src/scripts
    ports:
      - 8080:8000
    depends_on:
      - db
    # env_file:
    #   - .env.development
    working_dir: /src/scripts
    command: bash -c "./run.sh"
volumes:
  mysql_data:
